version: "2"

services:
  fe_db:
    image: wodby/mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
#    volumes:
#      - ./:/tmp

  fe_php:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    environment:
      PHP_SITE_NAME: fe
      PHP_DOCROOT: web
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
    volumes:
      - ./:/var/www/html

  fe_nginx:
    image: wodby/drupal-nginx:8-1.13
    environment:
      NGINX_BACKEND_HOST: fe_php
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_SERVER_NAME: localhost
      NGINX_UPSTREAM_NAME: fe_php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_DOCROOT: web
      DRUPAL_VERSION: 8
    volumes_from:
      - fe_php
    ports:
      - "9320:80"

  fe_pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: fe_db
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
     - "9321:80"
